## YAML Template.
---
server:
  port: 8080
  contextPath: /GoBananas
---
#spring:
#  profiles: local, default
#datasource:
#  gobananas:
#    url: jdbc:h2:~/root
#    username: root
#    password: tr@nzist0R!
#    driverClassName: org.h2.Driver
#    defaultSchema:
#    maxPoolSize: 10
#    hibernate:
#      hbm2ddl.method: create-drop
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: local, default
datasource:
  gobananas:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: tR@NZIST0r!
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
